SELECT * FROM EMPLOYEES;

-- 한 줄 주석
/*범위 주석*/
/*
 * TABLE명 앞에는 TBL 또는 TABLE을 작성하여
 * TABLE임을 알려준다.
 * */

CREATE TABLE TBL_MEMBER(
   MEMBER_NAME VARCHAR2(1000),
   MEMBER_AGE NUMBER
);

DROP TABLE TBL_MEMBER;

/*
 * 자동차 테이블 생성
 * 
 * -자동차 번호
 * -자동차 브랜드
 * -출시 날짜
 * -색상
 * -가격
 * 
 * */
CREATE TABLE TBL_CAR(
   CAR_NUMBER NUMBER CONSTRAINT PK_CAR PRIMARY KEY,
   /*CAR_NUMBER NUMBER PRIMARY KEY,*/
   CAR_BRAND VARCHAR2(1000),
   CAR_RELEASE_DATE DATE,
   CAR_COLOR VARCHAR2(1000),
   CAR_PRICE NUMBER(11)
);

ALTER TABLE TBL_CAR ADD CONSTRAINT PK_CAR PRIMARY KEY(CAR_NUMBER);
ALTER TABLE TBL_CAR DROP CONSTRAINT PK_CAR;
ALTER TABLE TBL_CAR DROP CONSTRAINT SYS_C007793;

DROP TABLE TBL_CAR;
/*
동물 테이블 생성

- 고유번호
- 종류
- 나이
- 먹이

- PK 제약조건을 부여해준다.
*/

CREATE TABLE TBL_ANIMAL(
ANIMAL_NUMBER NUMBER CONSTRAINT PK_ANIMAL PRIMARY KEY,
ANIMAL_TYPE VARCHAR2(1000),
ANIMAL_AGE NUMBER,
ANIMAL_FEED VARCHAR2(1000)
);

--컬럼 추가(성별 추가하기)
ALTER TABLE TBL_ANIMAL ADD(GENDER CHAR(1));
--컬럼 이름 수정(ANIMAL_NUMBER를 ANIMAL ID)
ALTER TABLE TBL_ANIMAL RENAME COLUMN ANIMAL_NUMBER TO ANIMAL_ID;
--컬럼 삭제(먹이 삭제)
ALTER TABLE TBL_ANIMAL DROP COLUMN ANIMAL_FEED;
--컬럼 수정(종류를 NUMBER로 변경)
ALTER TABLE TBL_ANIMAL MODIFY(ANIMAL_TYPE NUMBER);
--동물 테이블 삭제
DROP TABLE TBL_ANIMAL;

SELECT * FROM TBL_ANIMAL;

/*
-학생 테이블 생성
-학생 번호
-학생 아이디
-학생 이름
-전공
-성별
-생년월일
*/

CREATE TABLE TBL_STUDENT(
   STUDENT_NUMBER NUMBER CONSTRAINT PK_STUDENT PRIMARY KEY,
   STUDENT_ID VARCHAR2(1000) UNIQUE,
   STUDENT_NAME VARCHAR2(1000),
   STUDENT_MAJOR VARCHAR2(1000),
   /*STUDENT_GENDER CHAR(1) DEFAULT 'W' CONSTRAINT BAN_CHAR CHECK(STUDENT_GENDER = 'M' OR STUDENT_GENDER = 'W') NOT NULL,*/
   STUDENT_GENDER CHAR(1) DEFAULT 'W' CONSTRAINT BAN_CHAR CHECK(STUDENT_GENDER IN('M', 'W')) NOT NULL,
   STUDENT_BIRTH DATE CONSTRAINT BAN_DATE CHECK(STUDENT_BIRTH >= TO_DATE('1980-01-01', 'YYYY-MM-DD'))
);

--컬럼 추가(남친 여친 유무 검사)
ALTER TABLE TBL_STUDENT ADD(LOVER CHAR(1));

SELECT * FROM TBL_STUDENT;

DROP TABLE TBL_STUDENT;
